# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               CCO-510
tagline:             'Estruturas de Dados'
description:         ''
url:                 https://pmatias.me/cco510
baseurl:             /cco510
paginate:            5

# About/contact
author:
  name:              Paulo Matias
  url:               https://pmatias.me

# Custom vars
version:             1.0.0
